Repository crate/academy-fundamentals-course, pull requests merged in 2024-09, with the labels that each got.

#7 Fixed typo in geospatial hands-on.
  hands-on/fundamentals_handson_geospatial_data.html
Labels: bug

#13 Fix CrateDB typo
  subtitles/fundamentals_subtitles_data_modelling_time_series-en-US.vtt
Labels: bug

#12 Fix CrateDB typo
  subtitles/fundamentals_subtitles_data_modelling_geospatial-en-US.vtt
Labels: bug

#11 Fix CrateDB typo
  subtitles/fundamentals_subtitles_data_modelling_document_data-en-US.vtt
Labels: bug

#10 Fix CrateDB typo
  transcripts/ fundamentals_transcript_working_with_time_series_data.html
Labels: bug

#15 Added note about where to get a CrateDB cluster.
  notebooks/README.md
Labels: enhancement, cla-signed

#16 Remove unused tables from `REFRESH TABLE`
  notebooks/search/full_text_and_vector_search.ipynb
Labels: bug, cla-signed

#17 Added individual READMEs for each of the notebooks.
  notebooks/multi_model_data/README.md
  notebooks/search/README.md
  notebooks/timeseries/README.md
Labels: documentation, cla-signed

#18 Fixed typo in code commentary.
  notebooks/timeseries/timeseries_data.ipynb
Labels: bug, cla-signed
